services:
  gcs:
    profiles:
      - ""
      - sitl
      - simple
    extends:
      file: ./gcs-base-docker-compose.yaml
      service: gcs-base
    networks:
      - airstack_network
    ports:
      - 2222:22 # for ssh

  # ===================================================================================================================
  # for running on a real world laptop on the local network, set network mode to host
  gcs-real:
    profiles:
      - hitl
      - deploy
    extends:
      file: ./gcs-base-docker-compose.yaml
      service: gcs-base
    network_mode: host
    volumes:
      - $HOME/bags/:/bags
      - ../../robot/ros_ws/src/robot_bringup/rviz/:/bags/rviz
      - ../../plot:/plot
